#!/bin/bash
PHP_VERSION="${1}"

if [[ ${1} =~ ([0-9]+\.[0-9]+)\.[0-9]+ ]]; then
  PHP_SHORT_VERSION=${BASH_REMATCH[1]}
else
  echo "Wrong version number given"
  exit 1
fi

PHPBREW_PATH="/root/.phpbrew/"
PHPBREW_PHP_PATH="${PHPBREW_PATH}php/php-${1}/"
PHPBREW_MODULE_PATH="${PHPBREW_PATH}modules/"

phpbrew install ${PHP_VERSION} +dev +dbs
phpbrew ext install --pv ${PHP_VERSION} +dev
rm -R /root/.phpbrew/build/php-${PHP_VERSION}

declare -a module_list=('ioncube' 'zendguardloader' 'zendoptimizer')

for module_name in "${module_list[@]}"; do
  full_module_name=${PHPBREW_MODULE_PATH}${module_name}
  destination_file=${PHPBREW_PHP_PATH}lib/php/extensions/${module_name}.so

  if [[ -f ${full_module_name}.so ]] || [[ -f ${full_module_name}-php-${PHP_SHORT_VERSION}.so ]]; then
    if [[ -f ${full_module_name}.so ]]; then
      source_file=${full_module_name}.so
    elif [[ -f ${full_module_name}-php-${PHP_SHORT_VERSION}.so ]]; then
      source_file=${full_module_name}-php-${PHP_SHORT_VERSION}.so
    fi

    cp ${source_file} ${destination_file}

    ini_file=${PHPBREW_PHP_PATH}var/db/${module_name}.ini
    cp ${full_module_name}.ini ${ini_file}

    sed -i "s|<file>|${destination_file}|g" ${ini_file}
  fi
done